### ISSUE TITLE
"After" pd files?

### ISSUE THREAD

**Issue by djpeterso23662** [rickygraham/moogfest#1]
Hi @rickygraham!

Thanks for your great pd beginner's workshop at Moogfest!  It was very useful!  

The pace of the workshop was very brisk, so I was wondering if you could post a folder of "after" pd files here on GitHub to show how we should have ended up after doing our share of the typing, maybe with a couple extra comments?  I was not able to keep up with everything you were doing on the screen, so my final version files only have about 70% of what was in the lecture.  If you have time for this, I would really appreciate it!

Thanks, and thanks again for presenting at Moogfest!

David Peterson

**Comment by rickygraham** [comment]
Absolutely! I'll upload completed patches ASAP!

**Comment by rickygraham** [comment]
@djpeterso23662 - completed patches have been pushed. Enjoy!

**Comment by djpeterso23662** [comment]
Wow, @rickygraham, that was super-fast!  Thank you so much, I really appreciate it!

I am looking forward to getting deeper into PD.  Thanks again for your help!

David Peterson

**Comment by rickygraham** [comment]
You're welcome!
